site_name: InjectionMap

repo_url: https://github.com/InjectionMap/InjectionMap

pages:
- Introduction: index.md
- InjectionMap: injectionmap.md
- InjectionMap.Configuration: injectionmap.configuration.md
- InjectionMap.WPF: injectionmap.wpf.md
